import Foundation

/// Granularity of a token-usage measurement period.
enum UsagePeriod: String, Sendable, Codable {
    case today
    case thisWeek
    case thisMonth
}

/// Token consumption and optional cost data for services that expose raw
/// token metrics (e.g. Google Gemini, GitHub Copilot).
struct TokenUsageSummary: Sendable, Codable {
    /// Combined input + output token count.
    let totalTokens: Int

    /// Tokens consumed by prompts sent to the model.
    let inputTokens: Int

    /// Tokens generated by the model in responses.
    let outputTokens: Int

    /// Estimated cost in US dollars; `nil` when the service does not expose
    /// pricing information or the calculation is unavailable.
    let costUSD: Double?

    /// Time period this summary covers.
    let period: UsagePeriod
}
